### ISSUE TITLE
Non compatible avec windows

### ISSUE THREAD

**Issue by SebCanet** [braillerap/AccessBrailleRAP#1]
Bonjour,
ni yarn build ni yarn start ne fonctionnent sous windows, j'ai "ModuleNotFoundError: No module named 'serial'" comme message d'erreur.
Perso j'utilise corssenv.
Merci pour ce projet, je vais tâcher de voir comment il fonctionne et contribuer.

**Comment by crocsg** [comment]
Bonsoir
si c'est compatible Windows, je developpe avec :-)
A priori il manque une dependance python cote eel : la commande
pip install -r requirement.txt
(de preference dans un virtualenv) devrait resoudre le probleme

**Comment by SebCanet** [comment]
Super, ça marche, merci.

**Comment by SebCanet** [comment]
Je suis enseignant en BTS au lycée Livet de Nantes et j'ai eu vent de ce projet grâce à Michel, prof de techno à Rezé et partenaire de MHK depuis plusieurs années. Une équipe d'élèves travaille en projet à améliorer la BrailleRap et on a des idées sympa. Est ce que tu aurais un mail pour échanger là-dessus ? Merci.

**Comment by crocsg** [comment]
Je t'ai envoyé un mail avec mon contact
